name: CHECKS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "*"

jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    name: Run linter and tests on Linux
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run solhint
    - name: Run Tests
      run: npm test