name: CHECKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "*"

jobs:
  test_on_linux:
    runs-on: ubuntu-20.04
    name: Run linter and tests on Linux
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install solhint
      run: npm install -g solhint

    - name: Run solhint
      run: solhint **/*.sol --config ./.solhint.json -f json --max-warnings 0