name: Linter

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    solhint:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout teleporter
              uses: actions/checkout@v3

            - name: Install solhint
              run: |
                  npm install solhint -g
                  solhint --version

            - name: Run Lint
              run: |
                  cd contracts
                  solhint **/*.sol --config ./.solhint.json --ignore-path ./.solhintignore --max-warnings 0